### ISSUE TITLE
Reoccurring events not shown

### ISSUE THREAD

**Issue by lawrence-jeff** [franc6/ics_calendar#10]
I got this working but I notice reoccurring events (a weekly Monday event in this case) don't show up. Does this handle reoccurring events? This is specifically from outlook.com if that makes a difference

**Comment by franc6** [comment]
Recurring events should work, AFAIK. When I get some time to look at this again, I’ll be changing out which library it’s using, and I’ll add this to my testing list, to be sure it’s working, if possible. 

Thanks for the report!

TOM

-- 
Preserve wildlife -- pickle a squirrel!

**Comment by duncan-valleix** [comment]
In English
Hello, I see that you have declared the problem in fixed but I still have the concerns.

En Français
Bonjour, je vois que vous avez déclaré le problème en fixé mais j'ai toujours le soucis.

![image](https://user-images.githubusercontent.com/58829491/92350265-c19b3d00-f0d8-11ea-87fd-c11b0dc3161d.png)
![image](https://user-images.githubusercontent.com/58829491/92350271-c829b480-f0d8-11ea-8992-ba0bc08298b3.png)

**Comment by franc6** [comment]
@duncan-valleix The new calendar display in HA required some changes, see issue #15.  Please update and check if the newer version resolves this issue for you.  Thanks!

**Comment by franc6** [comment]
@lawrence-jeff When I checked, recurring events were displayed as expected.  There are a couple of different possibilities for why you were seeing problems.  If you can update and report back on if the problem is resolved or not, I would appreciate it.  Thanks!

**Comment by franc6** [comment]
@duncan-valleix & @lawrence-jeff Please try the 2.0.0-beta6 version instead, and see if that resolves at least the recurring events problems.  I think my server was generating the recurring events for me, and that's why I wasn't seeing that problem with the 1.x releases. :(

**Comment by lawrence-jeff** [comment]
I pulled your latest and it still doesn't work for me. It shows only on the first date. Here is an ICS that exhibits the issue

BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:TestReoccuring
BEGIN:VTIMEZONE
TZID:Central Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:\n
RRULE:FREQ=WEEKLY;UNTIL=20210318T220000Z;INTERVAL=1;BYDAY=TH;WKST=SU
UID:040000008200E00074C5B7101A82E008000000003C04126B4291D601000000000000000
 010000000AA857CE762BFA047BF62C1618D01F003
SUMMARY:Soccer
DTSTART;TZID=Central Standard Time:20200903T170000
DTEND;TZID=Central Standard Time:20200903T183000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20200923T004714Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR

**Comment by franc6** [comment]
Please use the released version 2.0.0 or later when it is available.

**Comment by franc6** [comment]
This appears to be working with when using the rie parser, or with icalevents in 2.0 until it was removed.
