### ISSUE TITLE
Feature request: Prefix for events

### ISSUE THREAD

**Issue by JOHLC** [franc6/ics_calendar#107]
Hi there!

Thank you for this component, it is excellent and I hope to see it continued to be developed. 

Would it be possible to request a feature to optionally allow adding a prefix to all events? 
My use case is that I have my work calendar shared, but only busy/free info. 
In Home Assistant, it shows only Busy which is not very useful since I am not sure which calendar that is attributed to: 

![image](https://github.com/franc6/ics_calendar/assets/63735432/ab90af22-a246-4c2e-aafa-7edf7343ee05)

Preferably, I could add a prefix to all events, for example if the prefix is "Testing" the event would appear like: 
![image](https://github.com/franc6/ics_calendar/assets/63735432/a96d3325-bc50-40f4-889d-ef26bd43b934)

**Comment by franc6** [comment]
That's a good use case.  I'll add it.

**Comment by franc6** [comment]
See version 4.1.0

**Comment by JOHLC** [comment]
I love this community. Thanks!
