### ISSUE TITLE
Calendar displayed in mobile is incorrect

### ISSUE THREAD

**Issue by homeautomator2** [franc6/ics_calendar#109]
First off, LOVE your app!  I use this to integrate an ICS calendar in my vacation rental home.  The house then "knows" when to wake up and go to sleep.  

The calendar displays perfectly on desktop.  However, on mobile (IOS), perhaps 1 in 10 entries displays incorrectly.  Currently i'm seeing an entry that is supposed to end on Nov 5 shows as ending on Nov 7.  There was one event in Oct that had the same behavior.  All the rest of the events show accurately in both places.  I just upgraded to 4.1.0 and the problem persists.  

Screenshots attached. 
![Screenshot 2023-11-09 at 9 10 21 AM](https://github.com/franc6/ics_calendar/assets/146100089/c7b0cd3b-8336-4d45-8ee6-79651c0d322a)
![IMG_0879](https://github.com/franc6/ics_calendar/assets/146100089/38de8ae7-592b-4937-8b76-63ea78a13de3)

**Comment by franc6** [comment]
If they always show correctly in your desktop browser, this is most likely a display problem, and should be reported to the main HA project.  If you see an automation going wrong, then it's probably not just a display problem.  Can you confirm?

Thanks!

**Comment by homeautomator2** [comment]
automation seems to fire correctly, so agree this is prob a display problem.  Am reporting to the main HA project now.  thx!

**Comment by franc6** [comment]
Thanks for the update.  If you open a github issue or post to the HA community forums, can you post a link to it here?  That way if it comes back as "it's more complex than a simple display problem, and the ics calendar component needs to change", it's easier to track the conversation.  Thanks!

**Comment by homeautomator2** [comment]
Opened an issue with HA main.  [Link is here](https://github.com/home-assistant/iOS/issues/2449)
