### ISSUE TITLE
start time and end time of workday

### ISSUE THREAD

**Issue by patrickgmail** [franc6/ics_calendar#110]
Hello
Is there any way to get daily : 
- the start time of the 1st event of the day
- the end time of the last event of the day.
- Thank you

**Comment by franc6** [comment]
That's really oustide the scope of this project -- there's no way for this integration to provide such functionality directly on its own.  Instead, the question is one that can be applied to any calendar platform.

Personally, I'd probably create an external script that uses the [HA REST API](https://developers.home-assistant.io/docs/api/rest/) to do whatever I wanted.  I've not paid much attention to all of the new automation stuff, but there might be something more interesting to you there.  I recommend asking on the [HA Community Forum](https://community.home-assistant.io), as you'll get a better range of responses.
