### ISSUE TITLE
weekday function missing

### ISSUE THREAD

**Issue by duczz** [franc6/ics_calendar#115]
can you add the weekday function? i wanna show up weekdays monday - sunday

`{{ (now().timestamp() - now().weekday() *86400) | int | timestamp_custom("%a %Y-%m-%d") }}`

**Comment by franc6** [comment]
This component doesn’t display anything, it simply makes the calendar entries available to Home Assistant. I’d suggest posting what you’d like to the HA Community Forums, it’s possible there already exists something to do what you want, and if not, that’s a more appropriate place to request such a feature. TOMOn Jan 4, 2024, at 5:39 AM, duczz ***@***.***> wrote:﻿
can you add the weekday function? i wanna show up weekdays monday - sunday
{{ (now().timestamp() - now().weekday() *86400) | int | timestamp_custom("%a %Y-%m-%d") }}
