### ISSUE TITLE
Add option to change calendar icon

### ISSUE THREAD

**Issue by Jinx735** [franc6/ics_calendar#126]
Hi, 
would it be possible to add an option to change the icon of the calendar?
Thats really all to my question.
Thanks ;)

**Comment by franc6** [comment]
Do you mean for an individual calendar, or for the integration itself?

**Comment by Jinx735** [comment]
For an individual calendar, like that:
![image](https://github.com/franc6/ics_calendar/assets/99906112/d11cbba0-d16e-4a0f-b093-b5d6492ff248)

**Comment by Jinx735** [comment]
Also another idea i got: Would it be possible, to somehow add extra dates/appointments to a calendar? Because I have a calendar (not administered by me) which has most of the dates, but not all of them.

**Comment by franc6** [comment]
I'm sorry, I thought I had replied to this a while ago.  For the icon, you should be able to change it through the UI AFTER the next release, which will allow for GUI configuration of the calendar entries.

As for updating the calendar, that's not possible with this integration, it's downloading a read-only file, there's no way for it to change that file.  However, you can use HA to create one or more local calendars, and add events to those.

**Comment by franc6** [comment]
This is fixed with version 5.0.0
