### ISSUE TITLE
Where to input calendars

### ISSUE THREAD

**Issue by Bloempottt** [franc6/ics_calendar#135]
I am pretty new to home assistant and notice that most explanations are difficult to follow. Could you please let me know where I need to put the calendar URLs? I have managed to install the ics calendar, but am a bit lost with all the different folders!

**Comment by franc6** [comment]
Please wait for version 5.0.0, and you can configure calendars through the UI, under Settings | Devices & services.  Click the Add Integration button near the bottom of the screen, and choose "ICS Calendar".
