### ISSUE TITLE
Some event titles not showing up in Home Assitant calendar screen

### ISSUE THREAD

**Issue by greyivy** [franc6/ics_calendar#15]
On the built-in Home Assistant calendar screen (https://[your-hostname]/calendar), some events have titles and others are blank (but their times still show up).

Looking at the code, I see an inconsistency between the names for the event title field.

https://github.com/franc6/ics_calendar/blob/4852ca2e2c1d5c5a9c65b8d22eb1c6a70cedd26a/custom_components/ics/calendar.py#L151

Solved by adding:

```python 
'summary': event.summary,
```

Not sure if this is an ideal solution, but it seems to work! Thank you for the excellent integration.

**Comment by franc6** [comment]
When I originally wrote this, it was modeled on the caldav platform, which, oddly, put title in one place, and summary in another.  It looks like the caldav platform has been modified to use summary in both places now, too.  I have yet to see the calendar page work at all -- nothing shows up for me, for any calendar, using this platform or the caldav platform. :(

**Comment by greyivy** [comment]
Weird! Regardless, thank you for the work you've put into this library. It's appreciated!
