### ISSUE TITLE
Error migrating calendar if connection_timeout is not set

### ISSUE THREAD

**Issue by ccMatrix** [franc6/ics_calendar#151]
I've updated ics_calendar from latest 4 to 5 and had the following error in the log:

```
2024-09-11 07:33:12.463 ERROR (SyncWorker_3) [homeassistant.helpers.json] Failed to serialize to JSON: /config/.storage/core.config_entries. Bad data at $.data.entries[97].data.connection_timeout=<object object at 0xf6347e08>(<class 'object'>
2024-09-11 07:33:12.470 ERROR (MainThread) [homeassistant.helpers.storage] Error writing config for core.config_entries: Failed to serialize to JSON: /config/.storage/core.config_entries. Bad data at $.data.entries[97].data.connection_timeout=<object object at 0xf6347e08>(<class 'object'>
```

I did not have `connection_timeout` set in the yaml configuration. After I saw the error I added a line `connection_timeout: 15` to the yaml and restarted home assistant which imported the yaml configuration into the core.config_entries file properly.

**Comment by Muenchen-Michi** [comment]
I had the same error, but did not recognize, that it's a problem with a missing settings in the old configuration, so I returned to version 4.2.0.

But this error is critical, because it stops HA from saving any new configuration. I added new integrations, that were all gone after a restart of HA. After going back to v4.2.0 and reinstalling my new integrations everything seems to work.
So I guess, v5.0.0 with the error writing the config is a severe problem, especially because you don't see in the log that this problem is caused by ics_calendar.

**Comment by wralb** [comment]
Thanks @ccMatrix, I also had to include the reference to connection_timout to get the migration to proceed.  I also found that new entities with _2 appended were created and I had to delete theold, and rename the new so they would work with all my templates and automations.

**Comment by franc6** [comment]
I've not been able to reproduce this one so far -- my own import data never included connection_timeout, since it's not something I've ever needed to adjust.  It'll probably be a while before I can get to this. :(

**Comment by ccMatrix** [comment]
I didn't have connection_timeout set before moving to 5.0.0 which is where the error came from. Setting it fixes it since then the default is no longer `None` which is an object it seems to have issues with serializing. 

I'm running Home Assistant on a Raspberry Pi 4 via Docker
HA version: 2024.9.1
Docker Image: ghcr.io/home-assistant/raspberrypi4-homeassistant:stable
OS: Ubuntu 22.04 LTS on aarch64 architecture

It is possible that this might be different when on e.g. x86/amd64. Maybe others with the same problem also have it on arm ?

**Comment by a351must2** [comment]
> Thanks @ccMatrix, I also had to include the reference to connection_timout to get the migration to proceed. I also found that new entities with _2 appended were created and I had to delete theold, and rename the new so they would work with all my templates and automations.

This is what I observed as well.  I had to create new ICS_Calendar entries, then I was able to see the old entities listed saying they were no longer provided by ICS Calendar.  I was able to delete the old entries and rename the new ones I added to get everything working.  I noticed as I was about to roll back to 4.2.0.

**Comment by franc6** [comment]
I would recommend going back to 4.2.0, anyway for now. I am curious, though it shouldn’t make any difference for serializing, is anyone who sees this running HA on x86-64?

**Comment by a351must2** [comment]
> I would recommend going back to 4.2.0, anyway for now. I am curious, though it shouldn’t make any difference for serializing, is anyone who sees this running HA on x86-64?

Yes, mine is on x86-64

**Comment by ccMatrix** [comment]
I see that in https://github.com/franc6/ics_calendar/blob/d51df8464ecabe01b5a918c0ed319da87692c139/custom_components/ics_calendar/calendardata.py#L62

The default value for connection_timeout is set to `_GLOBAL_DEFAULT_TIMEOUT`  which is imported from `socket`. IF I found the correct library then socket defines this as just `object()`:
https://github.com/python/cpython/blob/e9eedf19c99475b1940bbbbdc8816b51da3968e7/Lib/socket.py#L826

So this might be the reason why it tries to serialize an object?

I didn't 100% understand yet where and how the serialization/conversion from the yaml config to the entity for HA happens in the migration process.

**Comment by franc6** [comment]
Oh!  Great thought!  Look at https://github.com/franc6/ics_calendar/blob/d51df8464ecabe01b5a918c0ed319da87692c139/custom_components/ics_calendar/__init__.py#L259. I think that’s the problem. Try changing it to use `_GLOBAL_DEFAULT_TIMEOUT `. If you have the time, feel free to make a PR if you can test it, too. That’s really what it should be, not None, anyway. If you (or someone) can test that, I’d really appreciate it.

**Comment by franc6** [comment]
I'm blind; I can reproduce this, and the change above doesn't help.  If I can steal some time away today to work on this I will.

**Comment by ccMatrix** [comment]
My guess was that the object is initalized into a `CalendarData` object from the yaml which is then sent to HA for serialization into the entity store. There the connection_timeout is set to `_GLOBAL_DEFAULT_TIMEOUT` which probably isn't serializable by the json serializer. So you would have to set a different default there. None would work better since that can be serialized to null
