### ISSUE TITLE
Subscribed Calendars do not work in 5.0.0.

### ISSUE THREAD

**Issue by sven-debug** [franc6/ics_calendar#152]
I have several remote subscribed calendars and one local "subscription":

`ics_calendar:
  calendars:
    - name: "Abfallkalender 2024"
      url: "http://localhost:8123/local/Abfallkalender2024.ics"
      include_all_day: True
    - name: "Schulferien Baden-Württemberg"
      url: "https://www.feiertage-deutschland.de/kalender-download/ics/schulferien-baden-wuerttemberg.ics"
      include_all_day: true
    - name: "Schalke 04"
      url: "http://i.cal.to/ical/10/s04/bundesliga-spielplan/3298dd79.05e9d630-2cd86127.ics"
      include_all_day: true
    - name: "Feiertage Baden-Württemberg"
      url: "https://www.feiertage-deutschland.de/kalender-download/ics/feiertage-deutschland.ics"
      include_all_day: true`

Those do not work after the upgrade to 5.0.0. 

Re-Activating in YAML brings them back. Please double-check the migration routine.

**Comment by ingoratsdorf** [comment]
Same here.

**Comment by wralb** [comment]
The solution in #151 seems to allow yaml entries to be imported. I simply uncommented my yaml and followed the advice there, before removing the yaml again.

**Comment by franc6** [comment]
Which solution?  Changing the default for connection_timeout, or adding that option to your YAML?
