### ISSUE TITLE
Platform error calendar.ics - No module named 'arrow'

### ISSUE THREAD

**Issue by bbrendon** [franc6/ics_calendar#16]
I'm not really sure waht the issue is, but I'm guessing.... missing import?

```
root@ha:/opt/hass-prod-cfg# hacheck
Testing configuration at /opt/hass-prod-cfg
Failed config
  General Errors:
    - Platform error calendar.ics - No module named 'arrow'

Successful config (partial)
root@ha:/opt/hass-prod-cfg# alias
alias hacheck='/opt/python-venvs/hass/bin/hass -c /opt/hass-prod-cfg --script check_config'

root@ha:/opt/hass-prod-cfg/custom_components/ics# grep -Ri ver
__init__.py:from .calendar import VERSION
calendar.py:VERSION = "1.0.5"

```

**Comment by franc6** [comment]
Did you install via HACS?  If so, this is the same as issue #9, which I'll re-open.

**Comment by bbrendon** [comment]
Yes. I installed with hacs.

**Comment by bbrendon** [comment]
Does this make any sense? It doesn't to me but my python isn't great.
https://github.com/xerxes87/pyfujitsu_for_homeassistant/pull/2

**Comment by bbrendon** [comment]
This is interesting. After I did pip3 install arrow and pip3 install ics....

```
@ha  /opt/hass-prod-cfg/custom_components/ics  hacheck
Testing configuration at /opt/hass-prod-cfg
Failed config
  General Errors:
    - Platform error calendar.ics - No module named 'custom_components.ics.other'

Successful config (partial)
@ha  /opt/hass-prod-cfg/custom_components/ics  
```

**Comment by franc6** [comment]
No, those changes don't make sense to me with respect to the comment.  However, I could be missing something, and the changes make perfect sense. :(

Although, I just realized something else -- HACS modifies manifest.json based on the contents of requirements.txt, and I provide the requirements in both places.  Perhaps removing it from one or the other would do better?  The HACS documentation is unclear, but the HA documentation is (was, last I checked) very clear that requirements should be listed in manifest.json.

**Comment by franc6** [comment]
I really don't expect this is fixed, but I've made changes based on the comments above, and comments from the author of the PR mentioned above.

**Comment by bbrendon** [comment]
Luckily I still have it installed. I updated to 1.0.6 and uncommented the config.

```
root@ha:/opt/hass-prod-cfg# hacheck
Testing configuration at /opt/hass-prod-cfg
Failed config
  General Errors:
    - Platform error calendar.ics - No module named 'custom_components.ics.other'

Successful config (partial)
root@ha:/opt/hass-prod-cfg# 
```

**Comment by bbrendon** [comment]
I would think this issue should be easy to duplicate. Create a minimal python virtual env with the plugin and run it? Also make sure to disable most of the onboarding/default integrations.  I don't have `default_config` in my `configuration.yaml`

**Comment by franc6** [comment]
I think this is now resolved.  I cannot reproduce it anymore, even on a fresh install of HA 2022.8.5.
