### ISSUE TITLE
Template in URL not working 

### ISSUE THREAD

**Issue by freddeh** [franc6/ics_calendar#165]
Hi there.

With latest version installed and config via UI, using a URL with {year} as placeholder, I get 

Feiertage SH: Failed to open url(http://de-kalender.de/downloads/feiertage_schleswig-holstein_%7Byear%7D_et.ics): Not Found

Best regards
Frederik

**Comment by franc6** [comment]
Thanks for the report.  I'm 99.999% sure I know what's wrong.  For now, if you configure it via YAML instead, it should work.

Note to self: the code is running the URL through quote(), which ruins the templates.
