### ISSUE TITLE
ModuleNotFoundError: Platform ics_calendar.calendar not found

### ISSUE THREAD

**Issue by voronind-com** [franc6/ics_calendar#168]
Hass 2024.9.1, plugin 5.0.3

```txt
Sep 16 04:26:48 iot hass[370]: 2024-09-16 04:26:48.311 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for ics_calendar
Sep 16 04:26:48 iot hass[370]: Traceback (most recent call last):
Sep 16 04:26:48 iot hass[370]:   File "/nix/store/asjvw7bffk54aawfkvyq3a57psci7b37-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/config_entries.py", line 604, in async_setup
Sep 16 04:26:48 iot hass[370]:     result = await component.async_setup_entry(hass, self)
Sep 16 04:26:48 iot hass[370]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 16 04:26:48 iot hass[370]:   File "/var/lib/hass/custom_components/ics_calendar/__init__.py", line 202, in async_setup_entry
Sep 16 04:26:48 iot hass[370]:     await hass.config_entries.async_forward_entry_setups(entry, ["calendar"])
Sep 16 04:26:48 iot hass[370]:   File "/nix/store/asjvw7bffk54aawfkvyq3a57psci7b37-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2108, in async_forward_entry_setups
Sep 16 04:26:48 iot hass[370]:     await integration.async_get_platforms(platforms)
Sep 16 04:26:48 iot hass[370]:   File "/nix/store/asjvw7bffk54aawfkvyq3a57psci7b37-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/loader.py", line 1116, in async_get_platforms
Sep 16 04:26:48 iot hass[370]:     if platform := self._get_platform_cached_or_raise(platform_name):
Sep 16 04:26:48 iot hass[370]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 16 04:26:48 iot hass[370]:   File "/nix/store/asjvw7bffk54aawfkvyq3a57psci7b37-homeassistant-2024.9.1/lib/python3.12/site-packages/homeassistant/loader.py", line 1207, in _get_platform_cached_or_raise
Sep 16 04:26:48 iot hass[370]:     raise ModuleNotFoundError(
Sep 16 04:26:48 iot hass[370]: ModuleNotFoundError: Platform ics_calendar.calendar not found
```

**Comment by franc6** [comment]
The error seems to suggest the component isn’t correctly installed. Can you verify the files are installed as noted in [README.md](https://github.com/franc6/ics_calendar/blob/releases/README.md#Installation)?

**Comment by voronind-com** [comment]
> The error seems to suggest the component isn’t correctly installed. Can you verify the files are installed as noted in [README.md](https://github.com/franc6/ics_calendar/blob/releases/README.md#Installation)?

I install the extension via HACS. Is that alright? Old versions (before 5.0.0) worked, I've been using this plugin for a while.

**Comment by franc6** [comment]
As a general rule, yes, that’s a great way to install it.  Installation through HACS is the preferred method.  However, there have been reports of failed installs through HACS, both for this component and others (but it’s been years since I last heard of problems). Reinstalling fixed it. But that might not be your problem, which is why I asked if you can verify if all the files were installed.

**Comment by voronind-com** [comment]
> As a general rule, yes, that’s a great way to install it. Installation through HACS is the preferred method. However, there have been reports of failed installs through HACS, both for this component and others (but it’s been years since I last heard of problems). Reinstalling fixed it. But that might not be your problem, which is why I asked if you can verify if all the files were installed.

Sorry, sure I'll verify that all files are present. Tho I've tried reinstalling multiple times different versions.

**Comment by voronind-com** [comment]
@franc6 Well it looks like all files are present.
![image](https://github.com/user-attachments/assets/7b584bc5-7b3b-4d0b-9bac-2d446bcdc63d)

**Comment by voronind-com** [comment]
I am curious about this log line:
> `Error setting up entry  for ics_calendar`

Notice two spaces? Looks like entry name is empty. Should it be like that?

**Comment by voronind-com** [comment]
I just want to notify that I removed the plugin and have no plans on using it again. Which means that I won't be able to provide further info, sorry.

**Comment by franc6** [comment]
Please try the 5.0.4 pre-release version, to see if that fixes the problem.  I've changed how the dependencies are specified, and I have not seen the issue reported, but I also didn't see the problem before, either. :(

**Comment by voronind-com** [comment]
> Please try the 5.0.4 pre-release version, to see if that fixes the problem. I've changed how the dependencies are specified, and I have not seen the issue reported, but I also didn't see the problem before, either. :(

Noo, don't worry, I wasn't mean in my last message! :D 
I just dropped ICS in general. Sorry if that sounded aggressive.

Okay, I'll try to install it again just to report back to you. Thanks ♥️

**Comment by franc6** [comment]
@voronind-com Im sorry, I forgot you were the only one on this and that you had uninstalled. There’s another report of a similar (but possibly not exactly the same) problem that has multiple reporters. I just copy/pasted the earlier message to both. 
Please know I wasn’t at all offended, and my request was made without intending to ask that you start using it again, but merely to see if the new one fixes a problem you still have. Please accept my apologies for pasting the comment here without thinking. 

Thanks!

**Comment by franc6** [comment]
Closing as duplicate.
