### ISSUE TITLE
Some  of events missing & Wrong time

### ISSUE THREAD

**Issue by Resurrection2981** [franc6/ics_calendar#17]
![image](https://user-images.githubusercontent.com/45873933/93792138-b4995480-fc67-11ea-9f65-4c653557df1a.png)
![image](https://user-images.githubusercontent.com/45873933/93792194-c5e26100-fc67-11ea-8a5d-b416ba38c45d.png)

Google Calendar work well.

**Comment by franc6** [comment]
Can you share the actual calendar (with any personal details scrubbed, I suggest replacing titles/summaries and descriptions with English text like "title 1", "description 1", etc.  A plain text editor can be used to do that for you (obviously, I recommend a text editor that handles your characters correctly).

Additionally, which version are you using?

**Comment by Resurrection2981** [comment]
> Can you share the actual calendar (with any personal details scrubbed, I suggest replacing titles/summaries and descriptions with English text like "title 1", "description 1", etc. A plain text editor can be used to do that for you (obviously, I recommend a text editor that handles your characters correctly).
> 
> Additionally, which version are you using?

Sure. I use the latest version.

BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:课表
X-WR-TIMEZONE:Asia/Hong_Kong
BEGIN:VTIMEZONE
TZID:Asia/Shanghai
X-LIC-LOCATION:location
BEGIN:STANDARD
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
TZNAME:CST
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200914T140000
DTEND;TZID=Asia/Shanghai:20200914T153500
RRULE:FREQ=WEEKLY;UNTIL=20200928T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-f52f47c9-93e9-4cba-ae81-82b6c4558142
CREATED:20200906T170121Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170121Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200915T095500
DTEND;TZID=Asia/Shanghai:20200915T113000
RRULE:FREQ=WEEKLY;UNTIL=20200929T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-11585824-7b62-4dc8-bdb7-233b53e8f70e
CREATED:20200906T170121Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170121Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200907T080000
DTEND;TZID=Asia/Shanghai:20200907T093500
RRULE:FREQ=WEEKLY;UNTIL=20201019T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-5485f20b-d28b-4c6b-b081-a7424a904a45
CREATED:20200906T170121Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170121Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200908T080000
DTEND;TZID=Asia/Shanghai:20200908T093500
RRULE:FREQ=WEEKLY;UNTIL=20201027T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-efde1f15-0f72-4026-aea5-1f605a9c2943
CREATED:20200906T170122Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170122Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20201013T095500
DTEND;TZID=Asia/Shanghai:20201013T113000
RRULE:FREQ=WEEKLY;UNTIL=20201020T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-8bacd160-12aa-4b94-b7b4-df39b396b850
CREATED:20200906T170122Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170122Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200909T080000
DTEND;TZID=Asia/Shanghai:20200909T093500
RRULE:FREQ=WEEKLY;UNTIL=20201028T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-f7538a26-8abf-4e4f-9117-26e2fdf79c91
CREATED:20200906T170122Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170122Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20201012T140000
DTEND;TZID=Asia/Shanghai:20201012T153500
RRULE:FREQ=WEEKLY;UNTIL=20201019T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-ea6f31c8-2290-4ff7-af2c-9bc86247fae9
CREATED:20200906T170122Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170122Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200907T095500
DTEND;TZID=Asia/Shanghai:20200907T113000
RRULE:FREQ=WEEKLY;UNTIL=20201026T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-a3ee9fe9-9d7d-4e1f-bacf-4c58500c74a6
CREATED:20200906T170122Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170122Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200909T095500
DTEND;TZID=Asia/Shanghai:20200909T113000
RRULE:FREQ=WEEKLY;UNTIL=20201021T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-8c518666-2333-4bfb-a006-1c6af416bb2a
CREATED:20200906T170123Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170123Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200909T140000
DTEND;TZID=Asia/Shanghai:20200909T153500
RRULE:FREQ=WEEKLY;UNTIL=20201021T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-3d6cb25a-27bd-4997-9605-a8e8158f03a4
CREATED:20200906T170123Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170123Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20201014T155000
DTEND;TZID=Asia/Shanghai:20201014T163500
RRULE:FREQ=WEEKLY;UNTIL=20201021T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-56dde502-81c7-483c-8450-93cb1c499dfb
CREATED:20200906T170124Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170124Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200917T095500
DTEND;TZID=Asia/Shanghai:20200917T113000
RRULE:FREQ=WEEKLY;UNTIL=20200924T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-cf492106-753e-413f-9fb5-481a65c2a762
CREATED:20200906T170124Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170124Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20200910T080000
DTEND;TZID=Asia/Shanghai:20200910T093500
RRULE:FREQ=WEEKLY;UNTIL=20201022T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-a35705dc-4304-4d01-8831-1fb34c0b84ea
CREATED:20200906T170124Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170124Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Asia/Shanghai:20201008T095500
DTEND;TZID=Asia/Shanghai:20201008T113000
RRULE:FREQ=WEEKLY;UNTIL=20201029T160000Z;INTERVAL=1
DTSTAMP:20200921T133750Z
UID:WakeUpSchedule-4706d696-438a-432c-a02a-1f9ce4c6d370
CREATED:20200906T170124Z
DESCRIPTION:description5
LAST-MODIFIED:20200906T170124Z
LOCATION:location
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:summary
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

**Comment by franc6** [comment]
Thanks for the data!

Please specify the exact version number -- there are two different releases which could be considered "latest", 1.0.5 and 2.0.0-beta6. :)

In this case, though, I think you're probably using 1.0.5, and are seeing issue #10?  When I run through my tests, I see 14 events with 1.0.5, and 70 with 2.0.0-beta6.  It looks like the recurrence is not being parsed.  :( If you can confirm that the case, I'd appreciate it.  Then, please switch to the beta, which should work better.  If that's not the case, and it's missing non-recurring events, please let me know which events are missing.  You might need to redo the scrubbed data so the missing events are more clearly identified.

**Comment by Resurrection2981** [comment]
1.0.5. And yes, it's missing recurring events.
Beta version parse successfully, but got the wrong time, too.

**Comment by Resurrection2981** [comment]
> Thanks for the data!
> 
> Please specify the exact version number -- there are two different releases which could be considered "latest", 1.0.5 and 2.0.0-beta6. :)
> 
> In this case, though, I think you're probably using 1.0.5, and are seeing issue #10? When I run through my tests, I see 14 events with 1.0.5, and 70 with 2.0.0-beta6. It looks like the recurrence is not being parsed. :( If you can confirm that the case, I'd appreciate it. Then, please switch to the beta, which should work better. If that's not the case, and it's missing non-recurring events, please let me know which events are missing. You might need to redo the scrubbed data so the missing events are more clearly identified.

1.0.5. And yes, it's missing recurring events.
Beta version parse successfully, but got the wrong time, too.

**Comment by franc6** [comment]
This should be fixed when using the rie parser.
