### ISSUE TITLE
I think there is a variable missing in german translation (very small thing)

### ISSUE THREAD

**Issue by fft1010** [franc6/ics_calendar#170]
Hi,
I installed a new calendar, and it worked like a charm. Again: Many thanks for this. When it was enabled, I notices that this
![screen-2024-09-18-14-12-45](https://github.com/user-attachments/assets/4a96a6fb-bf75-4158-88e3-9db16db64f28)

is not really correct. It translates (somehow) to english as

configuration for X done
Where X is just the arrow in the picture. I assume there should go the name of the calender one created?
Calender is there, works fine, so it is not a big issue, but I stumbled over it, and this is only I can do to improve a little.

thanks
Juergen

**Comment by franc6** [comment]
A quick check shows it's also missing in English.  I'm pretty sure there's something missing on my side, and that it's not in the translation strings (which in this case, is from HA).  Thanks for the report!
