### ISSUE TITLE
Home Assistant 2024.10.1 seems to have broken this addon (and others)

### ISSUE THREAD

**Issue by q20** [franc6/ics_calendar#174]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version:

Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[X] x86-64

**Describe the bug**
After upgrading to Home Assistant 2024.10.1, the ICS Calendar integration fails to start:

```Logger: homeassistant.setup
Source: setup.py:269
First occurred: 15:58:06 (1 occurrences)
Last logged: 15:58:06

Setup failed for custom integration 'ics_calendar': Requirements for ics_calendar not found: ['ics>=0.7.2'].
```

I have attempted redownloading the addon, but this has not helped. The integration simply will not start.

This is one of _four_ addons unable to start after upgrading:

<img width="493" alt="image" src="https://github.com/user-attachments/assets/4cbcb90e-16b0-493a-8776-f3ca055032d6">

Which has me wondering if something is missing from the latest Home Assistant builds.

```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 15:58:06 (4 occurrences)
Last logged: 15:58:39

Setup failed for custom integration 'ics_calendar': Requirements for ics_calendar not found: ['ics>=0.7.2'].
Setup failed for custom integration 'somneo': Requirements for somneo not found: ['pysomneo==4.2.2'].
Setup failed for custom integration 'genius_lyrics': Requirements for genius_lyrics not found: ['lyricsgenius==3.0.1'].
Setup failed for custom integration 'peloton': Requirements for peloton not found: ['pylotoncycle==0.8.0'].
```

**Comment by q20** [comment]
PS: reverting to 2024.9.3 resolves all issues.

**Comment by franc6** [comment]
Typically, installation through HACS will install the dependencies. My guess is HA 2024.10.1 upgraded to a new python version, and perhaps either the install of dependencies failed, or those dependencies aren’t marked as working with the new version of python. The latter seems more likely to me, but I’m traveling today, and cannot check it out more. I’ll try to look into it later in the week. Thanks for the report!

**Comment by q20** [comment]
So, I have just updated ICS calendar to 5.0.4, upgraded HA to 2024.10.3 (from 2024.9.3) and I am faced with the same issues as before:

```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 12:03:58 (4 occurrences)
Last logged: 12:04:35

    Setup failed for custom integration 'genius_lyrics': Requirements for genius_lyrics not found: ['lyricsgenius==3.0.1'].
    Setup failed for custom integration 'somneo': Requirements for somneo not found: ['pysomneo==4.2.2'].
    Setup failed for custom integration 'ics_calendar': Requirements for ics_calendar not found: ['ics>=0.7.2'].
    Setup failed for custom integration 'peloton': Requirements for peloton not found: ['pylotoncycle==0.8.0'].
```

Any idea what could be going wrong here?

EDIT: actually, I may have an idea: after whitelisting pypi.org in Pi-hole, requirements are able to be installed.
Yup, whitelisting, updating, upgrading - it's all fine now.
Sorry for taking up your time. I'll leave this here in case anyone else ever has a similar issue.  👍
