### ISSUE TITLE
Issue with  2024.10.1 (and can't downgrade)

### ISSUE THREAD

**Issue by WordWireUK** [franc6/ics_calendar#176]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version: 2024.10.1

Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[X] ARM
[] x86-64

Since upgrading to 2024.10.1 this plugin fails to start.
Downgrading to 2024.9.3 doesn't seem to resolve. 
Any help / guidance as a workaround would be gratefully received. 
I think its a Python problem...?!

<img width="623" alt="Screenshot 2024-10-08 at 17 29 44" src="https://github.com/user-attachments/assets/594e4eeb-d1a3-42e0-a0e0-6e20895c1d18">

**Comment by franc6** [comment]
Please try the 5.0.4 pre-release version, to see if that fixes the problem.  I've changed how the dependencies are specified, and I have not seen the issue reported, but I also didn't see the problem before, either. :(

**Comment by WordWireUK** [comment]
> Please try the 5.0.4 pre-release version, to see if that fixes the problem. I've changed how the dependencies are specified, and I have not seen the issue reported, but I also didn't see the problem before, either. :(

Yes it fixed it!
Thank you so much.
