### ISSUE TITLE
How to delete "local calendar" added in Calendar UI

### ISSUE THREAD

**Issue by homeautomator2** [franc6/ics_calendar#181]
I was trying to add a 2nd calendar to the "Calendar" Dashboard and clicked on "Create Calendar".  This apparently creates a local calendar.  Now i want to delete this new, 2nd calendar.  I cannot find any documentation or info on how to do so.  i'm guessing edit YAML somewhere, but I can't find that location.

Anyone have an idea?

**Comment by franc6** [comment]
That’s not from this project. However, you should be able to go to settings, devices, and find the local calendar there and delete it. I don’t have access to my HA install at the moment, so I can’t be more specific. :(

**Comment by homeautomator2** [comment]
Thanks, but I’ve never setup a local calendar separately, so nothing shows up in settings->devices.  The ONLY visible remnant is on the calendar dashboard.  

 

You’re saying this is a core HA issue?

 

Thx for the assist!

 

Bill

**Comment by franc6** [comment]
Yes, it's a problem with HA core.  There's nothing in this project that ever lets you create a calendar, local, or otherwise.
