### ISSUE TITLE
Hide calendars column when there's only one calendar to show

### ISSUE THREAD

**Issue by tardich** [franc6/ics_calendar#187]
**Home Assistant Setup**
HA v2024.10.4, installed through HACS

Version:

Installation Type (put an X between the square brackets for your HA):
[] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[X] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[X] x86-64

**Describe the bug**
The calendars columns takes a fair amount of space in the screen, specifically when displayed in a tablet. We should have the option to hide this column as a global option, or on demand with a button a little bit like the "Home Assistant" sidebar

**Comment by franc6** [comment]
The sidebar you refer to isn't a part of this integration, but of Home Assistant itself.  Please send your feature request to them.  Thanks!
