### ISSUE TITLE
Filtering not working

### ISSUE THREAD

**Issue by the8thsign** [franc6/ics_calendar#192]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version:
Home Assistant 2024.11.2
ics_calendar 5.0.4 installed via HACS

Installation Type (put an X between the square brackets for your HA):
[] Home Assistant OS
[X] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[X] ARM
[] x86-64

**Describe the bug**
Filter does not seem to be working for me or maybe I just misunderstood how it's suppose to work. 

I'd like to filter just the events that have "No School" in the title, example: "No School - Thanksgiving Recess". I add ["no school"] in the include filter. The entire calendar is showing, example: "Early Dismissal" is currently showing. Should it be filtering that out or does the entity turn on if the filter matches and stays off if it doesn't?

**Comment by franc6** [comment]
The include filter is to include things that would otherwise be excluded. To see only events with [“No School”], put that in the include filter, and [“/.*/“] for the exclude filter. Maybe I should add an example for showing “only” matching events to the README…

TOM

**Comment by the8thsign** [comment]
This worked! Thank you. I did have to use ' instead of " incase anyone else runs across this.

**Comment by gieljnssns** [comment]
Thanks a lot, I was searching for the same.
