### ISSUE TITLE
Link in configuration section not working

### ISSUE THREAD

**Issue by dasEtwasmitPunkten** [franc6/ics_calendar#201]
I think the link in the configuration section should be [https://my.home-assistant.io/redirect/integrations/](https://my.home-assistant.io/redirect/integrations/) instead of [https://my.home-assistant.io/redirect/config/integrations/dashboard](https://my.home-assistant.io/redirect/config/integrations/dashboard). The current link sends me to a 404.

**Comment by franc6** [comment]
I think you're right.
