### ISSUE TITLE
Update breaks homeassistant

### ISSUE THREAD

**Issue by lordfiSh** [franc6/ics_calendar#203]
**Home Assistant Setup**
Version:
Core 2024.12.1
Supervisor 2024.12.0
Operating System 14.0
Frontend 20241127.6

Installation Type (put an X between the square brackets for your HA):
[x] Home Assistant OS

Hardware platform:
[x] x86-64

**Describe the bug**
After installing the latest update and restarting the webgui will not boot, the supervisor still works. 

supervisor shows errors 
![Bildschirmfoto 2024-12-16 um 18 34 43](https://github.com/user-attachments/assets/94ac50b3-d01a-4af5-a62b-338bdcebca32)

home assistant starts fine, but then get unresponsive after the following line

![Bildschirmfoto 2024-12-16 um 18 45 49](https://github.com/user-attachments/assets/f5f59b1f-db2e-458b-83c3-0a52f0c5f4a2)
stops after booting the component 

From the console
```
login
docker exec -it homeassistant bash
rm -r custom_components/ics_calendar/ 
exit
docker restart homeassistant
```

working again 

relevant: https://github.com/home-assistant/supervisor/issues/5477

**Comment by ThomasDesloovere** [comment]
Check issue #200 and install beta version
