### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by rgabrielson11** [franc6/ics_calendar#21]
Hello,

I have attempted to use both release and beta versions, but get this error;

2020-11-16 10:08:13 ERROR (SyncWorker_28) [custom_components.ics.calendar] FamilyCozi: Failed to parse ICS!

Ive PMed you on the HA forum with a copy of my ics file.  thanks

**Comment by franc6** [comment]
I can only reproduce the problem with the beta version, and it appears to be the same as issue #8 for that.  I won't mark this as a duplicate yet, pending confirmation that it can be reproduced in the non-beta version.  Please note that if you're installing via HACS, if you tried the beta version first, you have to remove the integration, remove the repository from HACS, re-add the repository to HACS and then install it again to get the non-beta version.

**Comment by rgabrielson11** [comment]
I had tried the non-beta first, had the same issue.  this is when I tried the beta and no change, so contact you.  thanks.

**Comment by rgabrielson11** [comment]
Switched to non-beta, works.  closing.
