### ISSUE TITLE
Rename component folder: Other folder in custo_components possible?

### ISSUE THREAD

**Issue by Friedi1970** [franc6/ics_calendar#35]
Hi,

I have the problem that I already have a component which needs the folder ics in custom_components. So, my question is if it would be possible to put it in another folder e.g. icscal.
If I do so, what do I need to change?

**Comment by franc6** [comment]
I believe you can rename the folder, and update manifest.json to change "domain" to match whatever you rename it.  Then, in your configuration.yaml, change the platform to match, too.  You can probably just rename the folder, but I'm not 100% certain of that, and I don't have the HA docs handy right now.  I hope that helps.  If you'd like to try just changing the name of the folder, let me know if it works, please, and I'll probably just change it here, too.

**Comment by Friedi1970** [comment]
Thanks! That worked well 👍
