### ISSUE TITLE
dont see items after 1-1-2022 and Please report it to the custom component author.

### ISSUE THREAD

**Issue by FinalX1992** [franc6/ics_calendar#42]
For me it doesnt see any calender items after 1-1-2022

also i get this error:

```
Entity calendar.kalender (<class 'custom_components.ics_calendar.calendar.ICSCalendarEventDevice'>) implements device_state_attributes. Please report it to the custom component author.
Entity calendar.vakantie (<class 'custom_components.ics_calendar.calendar.ICSCalendarEventDevice'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by franc6** [comment]
If you can upload a sample of the ICS file with event titles and descriptions changed (to remove any personal info), I can take a look at it in January.  

The warnings you see were previously reported as issue #40.  I have a fix for that, but I haven't made a release with it yet.  Thanks for the report, though.

**Comment by FinalX1992** [comment]
this is what i have in configuration.yaml
its open so nothing personal also another one but that is my main agenda both dont show anything after 1-2022

     - name: "vakantie"
        url: "https://agenda-abonnement.nl/feestdagen.ics"
        includeAllDay: True

**Comment by franc6** [comment]
I meant the actual ics file, not your configuration. :)

If you’re OK with that URL being open, I can download it from there later, although I’m concerned that later the problem might not show up quite the same way. 

Otherwise, you can remove the URL itself and upload the file. 

Thanks!

**Comment by FinalX1992** [comment]
feel free to use it its cloud hosted, its basicly a public holiday file

**Comment by Bjoernsen** [comment]
Unfortunately, I cannot see entries, too.

The problem is that I just installed, configured this integration, and added a card to list the entries today. So I cannot say if it once worked, or if I have an configuration issue.
You can use the URL for the ics. It is public available.

My configuration.yaml (some part):
```
calendar:
  - platform: ics_calendar
    calendars:
      - name: waste
        url: "https://abfall.nerdbridge.de/ical/abfall-nom-hardegsen-HM2W,PET,PAP,GL.ics"
        includeAllDay: True
```

**Comment by Bjoernsen** [comment]
Sorry my mistake. It took about 30 minutes for my home assistant installation to synchronize the calendar. It works now.

**Comment by franc6** [comment]
@FinalX1992 I cannot reproduce the problem using the default parser.  Using the ics parser, it won't display the New Year's Day event, but it looks like everything else works.  I believe the problem with the ics parser is an edge case for its timezone issues.  Also, unfortunately, there's a copyright notice in the file at the URL you provided, so I'll have to create my own file to track this problem.  If you don't see Carnivale show up in February, please let me know, as there must be more going on.  Thanks!

**Comment by FinalX1992** [comment]
i dont see carnival in february
it looks like its synchronizing only a week in advance like its showing max 1 week
like now i see Driekoningen on 6-1-2022 and nothing in february
i also dont see the new years eve thing anymore.

**Comment by franc6** [comment]
~~Interestingly, after a couple of restarts of HA, I was able to reproduce the problem.  After a few more restarts (and an update to 2021.12.7), I can't reproduce the problem again.  I don't see anything in the logs, either.~~

~~I'm guessing there's another problem somewhere, but it seems to be parsing the file just fine.  I have another calendar in which I'm seeing a similar issue, too.~~

Ignore the above; the problem after restarting was related to something else.  I'll make a release later today which I'm confident won't show the problem.  I just need to make a few adjustments to the dependencies, I think.

**Comment by franc6** [comment]
After more updates, I cannot reproduce this problem with the given calendar link and the latest versions of this project and Home Assistant.
Please re-open if you're still seeing a problem after updating to 2.1.2.
