### ISSUE TITLE
FEATURE REQUEST - add additional attributes

### ISSUE THREAD

**Issue by glassbase** [franc6/ics_calendar#44]
HA calendar entities support additional attributes such as message, location, description, start_time and end_time attributes, etc. 

Currently your component does not populate them. It would be awesome if you could add those. We could use this additional info to display calendar events start times, etc on dashboards.

(I only tested Google Calendar, but it appears to populate the start_ and end_time and the other attributes with the details of the current or next calendar event.)

Examples in documentation: [CalDAV](https://www.home-assistant.io/integrations/caldav/#sensor-attributes) and [Google](https://www.home-assistant.io/integrations/google/#sensor-attributes).

**Comment by franc6** [comment]
All of that information is reported, and looks to be available in my instance of HA still. If you’re not seeing it, something else is wrong. Can you provide more detail, specifically, what information do you see in HA, where do you see it in HA, and what is your configuration?  For the configuration, please replace any usernames and passwords with a single asterisk (*) and please truncate the Google URL, if it’s a public one. I’d also like a copy of the actual file, if you can include that. But please hide anything remotely private in it (e.g. replace place names, person names, and other personal details with nonsense. :)

Thanks!

**Comment by glassbase** [comment]
Maybe it is my ICS sources?

```
calendar:
  - platform: ics_calendar
    calendars:
      - name: "Juve (Serie A)"
        url: "https://api.thescore.com/seri/teams/6.ics"
```

All attributes on the calendar entity:
```
friendly_name: Juve (Serie A)
```

**Comment by glassbase** [comment]
Whereas, a Google Calendar entity (using the official Google Calendar integration), populates much more attributes:
```
message: Blue Jays @ Orioles
all_day: false
start_time: '2022-03-31 15:05:00'
end_time: '2022-03-31 18:05:00'
location: ''
description: ''
offset_reached: false
friendly_name: Toronto Blue Jays
```

**Comment by glassbase** [comment]
HANG ON, Looks like I somehow have 2 custom integrations for ICS. I appear to be using the other dev's (ics vs ics_calendar)

EDIT - switched over to your custom component and seeing same results.

**Comment by glassbase** [comment]
So to clarify, the calendar works. It shows in the HA calendar menu with all the events at the proper dates and times. 

All I am really talking about is (hopefully) -- adding the additional attributes to the calendar entity.

**Comment by franc6** [comment]
Thanks!  I understand, now.  This is the same as issue #43.  If an event were actually taking place (i.e. offset_reached is true), you'd see the other attributes.  You could also try switching the parser to icalevents, but that could introduce other issues, too.  The reason I suggest icalevents is that it will return the "next" event, no matter how far in the future and you'll see all the attributes as you expected.  This functionality is something I just haven't had time to implement, once I realized the new parser doesn't behave the same as icalevents in that regard.

**Comment by glassbase** [comment]
Thanks. Changing parser worked

**Comment by franc6** [comment]
@glassbase Please note version 2.6.0 adds a new "days" option for this purpose.  Set it to something greater than 1, you may need to experiment a little or look at how far apart your events tend to be.  Please note, too, that with version 2.6.0 using the icalevents parser will require the use of the new days option, as it now returns data in the same manner as the other two parsers.  I recommend removing the parser option and setting the days option with this update.
