### ISSUE TITLE
Ability to search events (request)

### ISSUE THREAD

**Issue by jane-t** [franc6/ics_calendar#53]
My local council provide an ics file with our bin collections.  As we have 3 bin types all on different cycles, It would be ideal if I could load the file 3 times to create "next collection" calendars for each of the 3 bins.

So a search option similar to that in the Google Calendar would be ideal https://www.home-assistant.io/integrations/google/#search

**Comment by franc6** [comment]
Please see v3.1.0, for the new include and exclude filters.
