### ISSUE TITLE
only synchronises 1 week the current one but not next week.

### ISSUE THREAD

**Issue by FinalX1992** [franc6/ics_calendar#54]
hello,
im writing this coz i notice, the addon only shows 1 week the current one i cannot see next week or anything after the current week.

**Comment by Dams51** [comment]
Hi,
I have the same issue

I looked in the code and it looks like it's the if statement [here](https://github.com/franc6/ics_calendar/blob/releases/custom_components/ics_calendar/calendar.py#L191-L195)

I never done that before but I'll try to make a Pull request
Done. #55

**Comment by franc6** [comment]
I’m sorry. I thought I replied to this a while ago. Where are you seeing this?  

@Dams51 The code you referenced stops it from downloading new events more than once every 15 minutes.

**Comment by Dams51** [comment]
The code I refered sotps it from computing the calendar data (cached or downloaded on call) more than once every 15 minutes.

The code that prevents data downloading is [there](https://github.com/franc6/ics_calendar/blob/releases/custom_components/ics_calendar/calendardata.py#L58-L60)

**Comment by franc6** [comment]
Right, I mistyped there. However, my question still remains. It all works for me, so I’m trying to understand what you are seeing. The change you proposed should do nothing at best. If it changes behavior, something else is wrong. :)

**Comment by Dams51** [comment]
I see the problem in lovelace using the calendar card
My preset view is list view so it show the current week events list but if you switch to next week it show an empty list because you must wait 15 minutes to update the list 
And if I open the calendar menu in the right panel it open in month view but with only the current week inside, nexts and previous month are empty

**Comment by franc6** [comment]
Thanks for the update!  I'll try to get to it this week, but I can't guarantee that (there's a lot going on).  Right now, the PR is fine, but will require some unit test updates, too.  If you want to update the unit tests, ensuring that each of the new branches is taken (and not taken), that would save me some time. :)

**Comment by franc6** [comment]
Please re-open if this is not fixed in 3.1.0.
