### ISSUE TITLE
new calendar events are not added to calendar view

### ISSUE THREAD

**Issue by o-l-o** [franc6/ics_calendar#56]
When I add new calendar event in the original calendar, I can see that the integration retrieves it (`calendar.<calendar_name>` entity returns something like this:
```
offset_reached: false
friendly_name: <calendar_name>
hide_attributes:
  - templates
message: Busy
all_day: false
start_time: '2022-06-25 12:45:00'
end_time: '2022-06-25 13:30:00'
location: ''
description: ''
```
).

However, the calendar view is not updated with this newly received event. It's also not recognized by automations. Is it expected behavior?

**Comment by franc6** [comment]
@o-l-o No, that's not intentional.  Please check version 3.0.1, which may have fixed this issue.  Thanks!

**Comment by o-l-o** [comment]
@franc6, now it seems to work correctly. Thank you.
