### ISSUE TITLE
Set Monday as default start day

### ISSUE THREAD

**Issue by Ra7t0r** [franc6/ics_calendar#61]
Hello
Similar to issue #27, is there a way to begin the week from Monday instead of Sunday?

<img width="1157" alt="Screenshot 2022-08-02 at 6 38 42 PM" src="https://user-images.githubusercontent.com/3109011/182415270-01a825b3-78f9-4753-934c-d52f049a081d.png">

**Comment by franc6** [comment]
This is an issue for HA.  This platform knows nothing about the start of a week, and indeed, has on concept of a "week".

See https://community.home-assistant.io/t/calendar-ability-to-select-the-first-day-of-the-week/197896/10 https://community.home-assistant.io/t/calendar-first-weekday-does-not-use-local-standard/217485/2 and https://github.com/home-assistant/frontend/discussions/5941 for information on how to change the start of the week in the calendar views.
