### ISSUE TITLE
Questions about the all-day event

### ISSUE THREAD

**Issue by chauyuen** [franc6/ics_calendar#66]
I have an ics file (generated using 
[icalendar-generator](https://github.com/spatie/icalendar-generator)) and below is part of it, I've only intercepted one of the events. I'm having a problem where this event will show up as a full day event on my iPhone, but it seems that rie will parse it as a normal event From 2022-09-01 0:00 to 2022-09-01 0:00. I'm wondering if it's a problem with RIE or if this doesn't comply with RFC 5545 and how I should fix it?

BEGIN:VCALENDAR
VERSION:2.0
PRODID:JBBot Calendar Creator
NAME:Demo
X-WR-CALNAME:Demo
DESCRIPTION:Demo V202210051449
X-WR-CALDESC:Demo V202210051449
REFRESH-INTERVAL;VALUE=DURATION:PT1440M
X-PUBLISHED-TTL:PT1440M
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:PRC
BEGIN:STANDARD
DTSTART:20211205T000000
TZOFFSETFROM:+0800
TZOFFSETTO:+0800
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:UTC
BEGIN:STANDARD
DTSTART:20211204T160000
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:JBBot-2022-09-01-5611
DTSTAMP:20220831T160000Z
SUMMARY:Rest Demo
STATUS:CONFIRMED
TRANSP:TRANSPARENT
DTSTART;TZID=PRC;VALUE=DATE:20220901
DTEND;TZID=PRC;VALUE=DATE:20220901
END:VEVENT

**Comment by chauyuen** [comment]
I wanted to let you know about some additional tests I did.
It is an all-day event when parser is set to ICS, but this does not work in rie

**Comment by franc6** [comment]
The RFC is pretty clear that DTEND is the non-inclusive end of the event.  An all day event for 2022-09-01 should have a DTSTART of 20220901, and a DTEND of 20220902 or perhaps no DTEND at all (but I suspect that might cause trouble for some parsers, too).
However, I really can't imagine what else the intent was.  So if the program generating the event isn't your own, let me know, and I believe I can modify my code to detect this case and treat it as an all-day event.

**Comment by chauyuen** [comment]
Thank you very much for your reply.
 I checked out some different calendars file and I decided to follow the requirements of RFC 5545.I will modify my code for generating calendar files to meet RFC 5545.Thank you so much for your help.
