### ISSUE TITLE
Just "Trying to decode strm!"

### ISSUE THREAD

**Issue by mcpfr** [franc6/ics_calendar#76]
Hello,

After a update to 3.1.6 version, all seems operated, but these is a error in log. Message is just ""Trying to decode strm!"

![image](https://user-images.githubusercontent.com/79054086/207419271-d6dc9814-0f20-460b-98c7-52dc6a87ea35.png)

Could you help me ?

**Comment by franc6** [comment]
Sometimes, it's just not my day. :(  It looks like I left some debugging code in place.  I'll have to fix this as soon as I get a chance.  For now, you can ignore the warning, it's completely spurious, and was used only while debugging the work-around for #75.

**Comment by mcpfr** [comment]
Courage !

Thank you for this quick feedback, I'm waiting for the update then

Thanks

**Comment by mcpfr** [comment]
I have delete: `self.logger.warning("Trying to decode strm!")` in def  `_decode_stream` in` calendardata.py` file
it's ok.
file is attached, you just have to replace it, my little participation so that your day is beautiful!!!
[calendardata.zip](https://github.com/franc6/ics_calendar/files/10221486/calendardata.zip)

**Comment by caraar12345** [comment]
Hey, thanks for a great integration which means I can integrate my work Pagerduty on-call schedule into Home Assistant without having to authenticate properly (and break a load of rules in the process..!). Having one error show up in my HA logs that actually isn't my fault for once is something I'd consider a good time 😂
