### ISSUE TITLE
Templating in URL

### ISSUE THREAD

**Issue by merlink01** [franc6/ics_calendar#77]
Is it possible to integrate templating into the url?
example:
url: "https://www.a-url?year={{now().year}}"

Currently I loaded multiple calendars for different years.

Thank you

**Comment by franc6** [comment]
Possible? yes.  Will I support templates that allow code?  No.  It's too easy to open up potential security issues that way (I can't think of any off the top of my head, but my assumption is someone else is better than me at such things).

However, I am willing to support some static templating options.  E.g., something like: https://www.a-url?year={year}

month and year seem obvious choices, but anything that needs a specific day of month seems like using the wrong technology to me.  What else can anyone think of that might be useful?  I'll leave this ticket open for the rest of the year for anyone to comment on with other ideas before I implement anything.

**Comment by merlink01** [comment]
Sounds good for me.
I cant see other variables currently, so year and month is great for me.

Thank you.
