### ISSUE TITLE
include/ exclude for only message attribute?

### ISSUE THREAD

**Issue by humanBeer** [franc6/ics_calendar#80]
So when i try to use regex to exclude certain characters in my calendar entries it excludes everything in the attributes. Basically I'm left with an empty calendar. I expected it to work by just filtering in the message attribute. Is there a way to just filter in the messages attribute?

I tried this: but it doesn't work

        exclude: "['(^[a-zA-Z]*)\\s']"
        include: "['message', 'all_day', 'start_time', 'end_time', 'location', 'description']"

**Comment by franc6** [comment]
I think you’ve misunderstood the filter feature. The idea is to filter out entire events based on matching strings in the event’s “SUMMARY” and “DESCRIPTION” fields. Your settings above, for example, would exclude any event whose summary or description starts with 0 or more letters, A-Z (case insensitive), unless the summary or description includes any of “message”, “all_day”, “start_time”, “end_time”, “location”, or “description”. It does **not** modify information in the event. Please see the [README.md] (https://github.com/franc6/ics_calendar#filters) file for more information.

**Comment by franc6** [comment]
@humanBeer Are you looking to modify the event description?  If so, do you want me to convert this to a request for a new feature?  Or am I completely misunderstanding what you've asked?

**Comment by franc6** [comment]
No response from OP, closing issue.
