### ISSUE TITLE
Request: Filter Exclude based on Time

### ISSUE THREAD

**Issue by spencerthayer** [franc6/ics_calendar#83]
Would it be possible to exclude events based on their time. Essentially I would like to remove events in any given day if they've already happened when the calendar is refreshed. Thanks!

**Comment by franc6** [comment]
I suspect you want to request a feature for whatever you are using to view the calendar's events.  This platform works properly, in that if you query it only for future events, it will return only future events.  That is not, however, what most things in HA do when showing you calendar events -- they instead request events that include past events, too.  Assuming that you're not running an API query against this platform, please submit a feature request to whatever component is used to view the calendar.

If I've misunderstood, and an API query doesn't correctly scope the events it returns, please re-open this issue, and include both your ICS file and the query you use, along with the actual output of the query.  If you have no idea what I mean by an API query, then you're almost certainly not doing that. :)
