### ISSUE TITLE
Error: Trying to decode strm!

### ISSUE THREAD

**Issue by Ra7t0r** [franc6/ics_calendar#85]
Hello.
I start to getting there errors and I notice that the calendar does not shown any events that exists on the ics url.

**:EDIT:
The events are updating from ics url, but I’m still getting these errors on the logs**

```
Logger: custom_components.ics_calendar.calendar
Source: custom_components/ics_calendar/calendardata.py:73 
Integration: ics_calendar ([documentation](https://github.com/franc6/ics_calendar), [issues](https://github.com/franc6/ics_calendar/issues)) 
First occurred: 6:27:38 PM (1 occurrences) 
Last logged: 6:27:38 PM

Trying to decode strm!
```

Any suggestions please?

**Comment by franc6** [comment]
See also issue #76.  That message isn't a real error, just some debug code, as attaching a real debugger isn't simple. It will be fixed in the next release, which I hope will be today, 2022-02-07.
