### ISSUE TITLE
Validation of configuration fails

### ISSUE THREAD

**Issue by DarthSonic** [franc6/ics_calendar#95]
As soon as I add the ics_calendar platform configuration to configuration.yaml, the validation in developer tools will check endlessly (it does not really fail, but also not succeed).

When I remove configuration, validation will succeed.

I am not willing to experiment and restart without successful validation ;-)

**Comment by DarthSonic** [comment]
Okay. After an additional restart (initially restarted after installed ics_calendar once). Validation works.

**Comment by franc6** [comment]
Please include the version of Home Assistant, as well as your config for this platform. Please do not include the actual URL, username, or password, but out in a placeholder for those values. Depending on your setup, and how easy it is to modify your config and restart HA (when HA is not running), it should be OK to restart and view the log file. However, if you aren’t comfortable with doing all of those things without HA running, I strongly recommend against restarting HA without a validation success. :). In either case, if validation hangs like that, you can usually view the log file to see what’s wrong. Sometimes that isn’t helpful, but often it is. :)On Aug 1, 2023, at 6:28 AM, Sven ***@***.***> wrote:﻿
As soon as I add the ics_calendar platform configuration to configuration.yaml, the validation in developer tools will check endlessly (it does not really fail, but also not succeed).
When I remove configuration, validation will succeed.
I am not willing to experiment and restart without successful validation ;-)
